---
language: ruby
cache: bundler
sudo: false

addons:
  apt:
    packages:
      - libarchive-dev
      - libarchive13

script: bundle exec rake travis
rvm:
  - 2.4
  - 2.5
branches:
  only:
    - master
matrix:
  fast_finish: true
